### PR TITLE
feat(task): adding support for new hook URL's of Slack

### PR DESCRIPTION
**Pull request by YouriT**

### CODE REVIEW

**Comment by SiamKreative** [comment]
+1

**Comment by YouriT** [comment]
The repo owner doesn't seem to be available for now...

In the mean time, I suggest you to put that in your package.json:
```
"grunt-slack-hook": "https://github.com/YouriT/grunt-slack-hook/tarball/c28dfd4f28b61ecef695cbb06a759d100bde0ae3"
```

**Comment by pwalczyszyn** [comment]
I would love to merge these, but there are changes also in the `package.info` which rename the project and URLs so I can't do it without cherry picking, which can get messy. 
Would love a single PR that just fixes the issues that I can merge with a single click of a button :smiley:

**Comment by YouriT** [comment]
Here you are @pwalczyszyn => #6 for a proper PR.

**Pull request closed without merging**
